# Generated by Django 5.2.10 on 2026-01-25 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('task_commented', 'Task Commented'), ('mention', 'Mentioned'), ('project_invite', 'Project Invitation'), ('team_invite', 'Team Invitation'), ('org_invite', 'Organization Invitation'), ('due_date_reminder', 'Due Date Reminder'), ('overdue', 'Task Overdue'), ('approval_needed', 'Approval Needed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('attachment_added', 'Attachment Added'), ('deadline_approaching', 'Deadline Approaching'), ('sprint_started', 'Sprint Started'), ('sprint_completed', 'Sprint Completed')], help_text='Type of notification', max_length=30)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Notification priority', max_length=10)),
                ('link_url', models.CharField(blank=True, help_text='URL to navigate to when clicked', max_length=500)),
                ('entity_type', models.CharField(blank=True, help_text='Type of related entity (task, project, etc.)', max_length=50)),
                ('entity_id', models.UUIDField(blank=True, help_text='ID of related entity', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('is_sent', models.BooleanField(default=False, help_text='Whether notification has been sent (for email/push)')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification data')),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('task_commented', 'Task Commented'), ('mention', 'Mentioned'), ('project_invite', 'Project Invitation'), ('team_invite', 'Team Invitation'), ('org_invite', 'Organization Invitation'), ('due_date_reminder', 'Due Date Reminder'), ('overdue', 'Task Overdue'), ('approval_needed', 'Approval Needed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('attachment_added', 'Attachment Added'), ('deadline_approaching', 'Deadline Approaching'), ('sprint_started', 'Sprint Started'), ('sprint_completed', 'Sprint Completed')], help_text='Type of notification this preference applies to', max_length=30)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS')], help_text='Delivery channel', max_length=10)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this notification type is enabled for this channel')),
                ('send_immediately', models.BooleanField(default=True, help_text='Send immediately or batch')),
                ('user', models.ForeignKey(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
                'ordering': ['notification_type', 'channel'],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS')], help_text='Delivery channel', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', help_text='Queue status', max_length=20)),
                ('scheduled_for', models.DateTimeField(help_text='When to send this notification')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was actually sent', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('notification', models.ForeignKey(help_text='Notification to be sent', on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification Queue Entry',
                'verbose_name_plural': 'Notification Queue Entries',
                'db_table': 'notification_queue',
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_63f199_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['entity_type', 'entity_id'], name='notificatio_entity__519f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_8fa075_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'is_enabled'], name='notificatio_user_id_527ac2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'notification_type', 'channel')},
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_27f60e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['channel', 'status'], name='notificatio_channel_3e54a3_idx'),
        ),
    ]
