# Generated by Django 5.2.10 on 2026-01-24 11:38

import apps.core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived'), ('pending', 'Pending Verification')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ja', 'Japanese')], default='en', help_text='Preferred language for UI', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last user activity timestamp', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Notification preferences (email, in-app, etc.)'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User preferences (theme, layout, etc.)'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completion',
            field=models.IntegerField(default=0, help_text='Profile completion percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text='User timezone for date/time display', max_length=50, validators=[apps.core.utils.validators.validate_timezone]),
        ),
        migrations.AddField(
            model_name='user',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, help_text='User working hours configuration'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='users_email_a7cfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_status', 'is_deleted'], name='users_account_471ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-last_activity'], name='users_last_ac_be241a_idx'),
        ),
    ]
