# Generated by Django 5.2.10 on 2026-01-24 13:11

import apps.core.utils.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Team name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Team description')),
                ('color', models.CharField(default='#10B981', help_text='Team color (hex)', max_length=7, validators=[apps.core.utils.validators.validate_hex_color])),
                ('icon', models.CharField(blank=True, help_text='Team icon identifier', max_length=50)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('secret', 'Secret')], default='public', help_text='Team visibility level', max_length=20)),
                ('member_count', models.IntegerField(default=0, help_text='Current number of members')),
                ('project_count', models.IntegerField(default=0, help_text='Number of assigned projects')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, help_text='Team lead/manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('maintainer', 'Maintainer'), ('member', 'Member')], default='member', help_text='Member role in team', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Date when user joined team')),
                ('last_active_at', models.DateTimeField(blank=True, help_text='Last activity in team context', null=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_team_members', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='Team', on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='tasks.team')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'team_members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(help_text='Team members', related_name='teams', through='tasks.TeamMember', through_fields=('team', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'role'], name='team_member_team_id_ff613b_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['user'], name='team_member_user_id_906d63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'user')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['organization', 'visibility'], name='teams_organiz_23b24c_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['lead'], name='teams_lead_id_6c6208_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('organization', 'name')},
        ),
    ]
