# Generated by Django 5.2.10 on 2026-01-24 13:22

import apps.core.utils.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Project name', max_length=255)),
                ('key', models.CharField(help_text='Project key/identifier (e.g., PROJ)', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Project description')),
                ('color', models.CharField(default='#3B82F6', help_text='Project color (hex)', max_length=7, validators=[apps.core.utils.validators.validate_hex_color])),
                ('icon', models.CharField(blank=True, help_text='Project icon identifier', max_length=50)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', help_text='Project status', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Project priority', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('secret', 'Secret')], default='private', help_text='Project visibility level', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Project due date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When project was completed', null=True)),
                ('member_count', models.IntegerField(default=0, help_text='Current number of members')),
                ('task_count', models.IntegerField(default=0, help_text='Total number of tasks')),
                ('open_task_count', models.IntegerField(default=0, help_text='Number of open tasks')),
                ('completed_task_count', models.IntegerField(default=0, help_text='Number of completed tasks')),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, help_text='Completion percentage (0-100)', max_digits=5)),
                ('is_template', models.BooleanField(default=False, help_text='Whether this is a project template')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Project-specific settings and preferences')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, help_text='Project owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Assigned team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='tasks.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', help_text='Member role in project', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Date when user joined project')),
                ('last_active_at', models.DateTimeField(blank=True, help_text='Last activity in project context', null=True)),
                ('custom_permissions', models.JSONField(blank=True, default=dict, help_text='Custom permissions for this member')),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_project_members', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='tasks.project')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Member',
                'verbose_name_plural': 'Project Members',
                'db_table': 'project_members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(help_text='Project members', related_name='projects', through='tasks.ProjectMember', through_fields=('project', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'role'], name='project_mem_project_0d0b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user'], name='project_mem_user_id_f59cbb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'user')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='projects_organiz_ca8931_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'visibility'], name='projects_organiz_348f36_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team'], name='projects_team_id_f935b2_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='projects_owner_i_c299b3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['due_date'], name='projects_due_dat_67b3bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('organization', 'key')},
        ),
    ]
