# Generated by Django 5.2.10 on 2026-01-24 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tasks', '0002_project_projectmember_project_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Task title', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Task description')),
                ('task_number', models.IntegerField(help_text='Sequential task number within project')),
                ('task_type', models.CharField(choices=[('task', 'Task'), ('bug', 'Bug'), ('feature', 'Feature'), ('epic', 'Epic'), ('story', 'Story'), ('subtask', 'Subtask')], default='task', help_text='Task type', max_length=20)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', help_text='Task status', max_length=20)),
                ('priority', models.CharField(choices=[('lowest', 'Lowest'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('highest', 'Highest')], default='medium', help_text='Task priority', max_length=20)),
                ('labels', models.JSONField(blank=True, default=list, help_text='Task labels/tags')),
                ('start_date', models.DateField(blank=True, help_text='Task start date', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Task due date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When task was completed', null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours to complete', max_digits=6, null=True)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Actual hours spent', max_digits=6)),
                ('comment_count', models.IntegerField(default=0, help_text='Number of comments')),
                ('attachment_count', models.IntegerField(default=0, help_text='Number of attachments')),
                ('subtask_count', models.IntegerField(default=0, help_text='Number of subtasks')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Custom field values')),
                ('assignee', models.ForeignKey(blank=True, help_text='Currently assigned user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('blocked_by', models.ManyToManyField(blank=True, help_text='Tasks blocking this task', related_name='blocking_tasks', to='tasks.task')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('parent_task', models.ForeignKey(blank=True, help_text='Parent task for subtasks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='tasks.task')),
                ('project', models.ForeignKey(help_text='Project this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project')),
                ('reporter', models.ForeignKey(blank=True, help_text='User who created the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tasks', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('priority_changed', 'Priority Changed'), ('due_date_changed', 'Due Date Changed'), ('completed', 'Completed'), ('reopened', 'Reopened')], help_text='Type of activity', max_length=30)),
                ('description', models.TextField(help_text='Activity description')),
                ('old_value', models.JSONField(blank=True, help_text='Previous value', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New value', null=True)),
                ('task', models.ForeignKey(help_text='Task this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Activity',
                'verbose_name_plural': 'Task Activities',
                'db_table': 'task_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Uploaded file', upload_to='tasks/attachments/%Y/%m/%d/')),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type', max_length=100)),
                ('description', models.TextField(blank=True, help_text='File description')),
                ('task', models.ForeignKey(help_text='Task this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Attachment',
                'verbose_name_plural': 'Task Attachments',
                'db_table': 'task_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Comment content')),
                ('is_edited', models.BooleanField(default=False, help_text='Whether comment was edited')),
                ('edited_at', models.DateTimeField(blank=True, help_text='When comment was last edited', null=True)),
                ('author', models.ForeignKey(help_text='Comment author', on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Parent comment for replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tasks.taskcomment')),
                ('task', models.ForeignKey(help_text='Task this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Task Comment',
                'verbose_name_plural': 'Task Comments',
                'db_table': 'task_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='tasks_project_fe19a5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'assignee'], name='tasks_project_d7b29e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='tasks_assigne_972e70_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='tasks_priorit_a9efa1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='tasks_due_dat_0359a9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent_task'], name='tasks_parent__ebc03e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'task_number')},
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['task', '-created_at'], name='task_activi_task_id_e45ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['user'], name='task_activi_user_id_b546c1_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['activity_type'], name='task_activi_activit_d2926a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['task'], name='task_attach_task_id_637c08_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['uploaded_by'], name='task_attach_uploade_02cb7c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='task_commen_task_id_413a08_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['author'], name='task_commen_author__dbe0d1_idx'),
        ),
    ]
