# Generated by Django 5.2.10 on 2026-01-24 14:22

import apps.core.utils.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tasks', '0003_task_taskactivity_taskattachment_taskcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Workflow name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Workflow description')),
                ('is_default', models.BooleanField(default=False, help_text='Default workflow for new projects')),
                ('is_system', models.BooleanField(default=False, help_text='System workflow (cannot be deleted)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether workflow is active')),
                ('created_by', models.ForeignKey(help_text='User who created the workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Project-specific workflow (null for organization-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='tasks.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'db_table': 'workflows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Rule name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Rule description')),
                ('trigger_type', models.CharField(choices=[('status_changed', 'Status Changed'), ('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_assigned', 'Task Assigned'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('due_date_approaching', 'Due Date Approaching'), ('due_date_passed', 'Due Date Passed')], help_text='What triggers this rule', max_length=30)),
                ('trigger_config', models.JSONField(blank=True, default=dict, help_text='Trigger-specific configuration')),
                ('conditions', models.JSONField(blank=True, default=list, help_text='Conditions that must be met')),
                ('actions', models.JSONField(blank=True, default=list, help_text='Actions to perform when triggered')),
                ('is_active', models.BooleanField(default=True, help_text='Whether rule is active')),
                ('priority', models.IntegerField(default=0, help_text='Execution priority (higher = earlier)')),
                ('execution_count', models.IntegerField(default=0, help_text='Number of times rule has been executed')),
                ('last_executed_at', models.DateTimeField(blank=True, help_text='Last execution timestamp', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created the rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_rules', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(help_text='Workflow this rule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='tasks.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Rule',
                'verbose_name_plural': 'Workflow Rules',
                'db_table': 'workflow_rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='State name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='State description')),
                ('category', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], help_text='State category', max_length=20)),
                ('color', models.CharField(default='#6B7280', help_text='State color (hex)', max_length=7, validators=[apps.core.utils.validators.validate_hex_color])),
                ('is_initial', models.BooleanField(default=False, help_text='Initial state for new tasks')),
                ('is_final', models.BooleanField(default=False, help_text='Final/completed state')),
                ('display_order', models.IntegerField(default=0, help_text='Display order in UI')),
                ('workflow', models.ForeignKey(help_text='Workflow this state belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='tasks.workflow')),
            ],
            options={
                'verbose_name': 'Workflow State',
                'verbose_name_plural': 'Workflow States',
                'db_table': 'workflow_states',
                'ordering': ['workflow', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Transition name (e.g., 'Start Progress', 'Complete')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Transition description')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Conditions that must be met for transition')),
                ('actions', models.JSONField(blank=True, default=list, help_text='Actions to perform on transition')),
                ('requires_comment', models.BooleanField(default=False, help_text='Whether transition requires a comment')),
                ('display_order', models.IntegerField(default=0, help_text='Display order in UI')),
                ('from_state', models.ForeignKey(help_text='Source state', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='tasks.workflowstate')),
                ('to_state', models.ForeignKey(help_text='Target state', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='tasks.workflowstate')),
                ('workflow', models.ForeignKey(help_text='Workflow this transition belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='tasks.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Transition',
                'verbose_name_plural': 'Workflow Transitions',
                'db_table': 'workflow_transitions',
                'ordering': ['workflow', 'display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['organization', 'is_active'], name='workflows_organiz_5ab487_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['project'], name='workflows_project_ae1218_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['is_default'], name='workflows_is_defa_b1ca50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflow',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='workflowrule',
            index=models.Index(fields=['workflow', 'is_active'], name='workflow_ru_workflo_db3807_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrule',
            index=models.Index(fields=['trigger_type'], name='workflow_ru_trigger_51047c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrule',
            index=models.Index(fields=['-priority'], name='workflow_ru_priorit_20dc26_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstate',
            index=models.Index(fields=['workflow', 'display_order'], name='workflow_st_workflo_d08692_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstate',
            index=models.Index(fields=['workflow', 'is_initial'], name='workflow_st_workflo_095171_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstate',
            index=models.Index(fields=['workflow', 'is_final'], name='workflow_st_workflo_16218b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstate',
            unique_together={('workflow', 'name')},
        ),
        migrations.AddIndex(
            model_name='workflowtransition',
            index=models.Index(fields=['workflow'], name='workflow_tr_workflo_ba01a6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtransition',
            index=models.Index(fields=['from_state'], name='workflow_tr_from_st_d55c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtransition',
            index=models.Index(fields=['to_state'], name='workflow_tr_to_stat_8a2a93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowtransition',
            unique_together={('workflow', 'from_state', 'to_state')},
        ),
    ]
