# Generated by Django 5.2.10 on 2026-01-24 11:57

import apps.core.utils.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Organization name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly organization identifier', max_length=255, unique=True, validators=[apps.core.utils.validators.validate_slug])),
                ('description', models.TextField(blank=True, help_text='Organization description')),
                ('logo', models.ImageField(blank=True, help_text='Organization logo', null=True, upload_to='organizations/logos/')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Primary brand color (hex)', max_length=7, validators=[apps.core.utils.validators.validate_hex_color])),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial'), ('expired', 'Expired')], db_index=True, default='trial', max_length=20)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Organization settings')),
                ('max_members', models.IntegerField(default=10, help_text='Maximum number of members', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_projects', models.IntegerField(default=5, help_text='Maximum number of projects', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_storage_gb', models.IntegerField(default=5, help_text='Maximum storage in GB', validators=[django.core.validators.MinValueValidator(1)])),
                ('current_members', models.IntegerField(default=1, help_text='Current number of members', validators=[django.core.validators.MinValueValidator(0)])),
                ('current_projects', models.IntegerField(default=0, help_text='Current number of projects', validators=[django.core.validators.MinValueValidator(0)])),
                ('current_storage_gb', models.DecimalField(decimal_places=2, default=0, help_text='Current storage usage in GB', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='Trial end date', null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, help_text='Subscription end date', null=True)),
                ('verified', models.BooleanField(default=False, help_text='Organization verification status')),
                ('domain', models.CharField(blank=True, help_text='Verified domain for SSO', max_length=255)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Organization owner', on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], db_index=True, default='member', help_text='Member role', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('suspended', 'Suspended')], db_index=True, default='active', help_text='Membership status', max_length=20)),
                ('custom_permissions', models.JSONField(blank=True, default=dict, help_text='Custom role permissions override')),
                ('invitation_token', models.CharField(blank=True, help_text='Invitation token', max_length=255)),
                ('invitation_expires_at', models.DateTimeField(blank=True, help_text='Invitation expiration date', null=True)),
                ('joined_at', models.DateTimeField(blank=True, help_text='Date when user accepted invitation', null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Last time user accessed this organization', null=True)),
                ('invited_by', models.ForeignKey(blank=True, help_text='User who sent the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Member',
                'verbose_name_plural': 'Organization Members',
                'db_table': 'organization_members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(help_text='Organization members', related_name='organizations', through='organizations.OrganizationMember', through_fields=('organization', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['organization', 'role'], name='organizatio_organiz_f18a08_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['user', 'status'], name='organizatio_user_id_ff073d_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['invitation_token'], name='organizatio_invitat_091be8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'user')},
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='organizatio_slug_5b8b37_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status', 'is_deleted'], name='organizatio_status_21c6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['owner'], name='organizatio_owner_i_0051c7_idx'),
        ),
    ]
